### ISSUE TITLE
User Creation Error

### ISSUE THREAD

**Issue by zaktecs** [FabriDamazio/amplifier#23]
Hi Fabir,

Thanks for the starter pack. I'm having the following issues when I try to create a user.  I hope you will be able to help me with.  I'm not using an API just a standard asp.net core 2.2 MVC application.  Please see below the error I get when I try to save a user record to the AspNetUsers table

SqlException: The INSERT statement conflicted with the FOREIGN KEY SAME TABLE constraint "FK_AspNetUsers_AspNetUsers_CreationUser". The conflict occurred in database "ClaritysmsDB", table "dbo.AspNetUsers", column 'Id'.
 The statement has been terminated.

I still get this error even passing a user Id to this column (CreationUser)

Kind Regards, 

Zak

**Comment by zaktecs** [comment]
HI @FabriDamazio 
Thanks for your response. Yes I have created a default user (admin) already in the seed database (SeedDataBase(modelBuilder);. Please find below my code for creating a user:

 UserDto userDto = new UserDto();
 userDto.Email = student.Email;
 userDto.PhoneNumber = student.PhoneNumber;
 userDto.UserName = student.Email;
 await _userAppService.Create(userDto, pwd);

Many thanks
Zak

**Comment by FabriDamazio** [comment]
Can you check the userDto Id property? It should be 0 before call Create in service.

**Comment by zaktecs** [comment]
Yes, it is zero when passing in the userDto. I'm able to create a record when I take this out from the Object "IFullAuditedEntity,".  the same thing happens to all my objects where IFullAuditedEntity, is implemented.
Many thanks
zak

**Comment by FabriDamazio** [comment]
Ok, Zak.

Are logged as tenant or host when creating records? Do errors happen in both?
Can you provide the code of your User, UserDto and UserAppService classes?

**Comment by zaktecs** [comment]
I'm logging in with the default admin created with seed. I have created a tenant and updated my user account with tenant id

[Clarity.zip](https://github.com/FabriDamazio/amplifier/files/2797401/Clarity.zip)

Many thanks

zak

**Comment by FabriDamazio** [comment]
@zaktecs you user UserId should be the id of the logged user.
Did you added `app.UseAmplifier<int>();` in your Configure method in Startup.cs file?

**Comment by zaktecs** [comment]
Yes I doSee below this from Configure section
           app.UseAmplifier<int>();
            app.UseAuthentication();
            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseHttpsRedirection();
 ========================
After stepping through the code again I can see that the values are getting set but when I get redirected to my home page I lose all the values. when it step pass the below code in the startup.cs
==============================
 services.AddDbContext<ClaritysmsDbContext>(options =>
              options.UseSqlServer(Configuration.GetConnectionString("Default"),
                   b => b.MigrationsAssembly("Claritysms.API")
              ));
===============.

Maybe I'm not setting something right.  Can I share my screen with you if you don't mind?

Many thanks

Zak
![useridissethere](https://user-images.githubusercontent.com/10104562/51778589-72b6b480-20fa-11e9-9bc1-20dbd7ce9d0e.GIF)

**Comment by FabriDamazio** [comment]
@zaktecs we are close to solving this. 

1 - Can you please put your `app.UseAmplifier();` AFTER `app.UseAuthentication();` and test it
2 - Can you confirm if you are using the latest version of Amplifier package? (0.5.0)

**Comment by zaktecs** [comment]
@FabriDamazio I'm using 0.5.0
 <PackageReference Include="Amplifier.AspNetCore" Version="0.5.0" />
 <PackageReference Include="Amplifier.EntityFrameworkCore" Version="0.5.0" />

When I move app.UseAmplifier(); below app.UseAuthentication(); I get the following error:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Amplifier.AspNetCore.Authentication.ApplicationBuilderExtensions.UserSessioMiddleware`1.InvokeAsync(HttpContext context, IUserSession`1 session)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by FabriDamazio** [comment]
You ConfigureServices method in Startup.cs have `services.AddAmplifier();` ?

**Comment by zaktecs** [comment]
@FabriDamazio Yes I do: see below

 services.AddAmplifier();
            services.AddScoped<ITenantManager, TenantManager>();
            services.AddScoped<IUserManager, UserManager>();
            services.AddScoped<IRoleManager, RoleManager>();
            services.AddScoped<ILoginManager, LoginManager>();
            services.AddScoped(typeof(IRepositoryBase<,>), typeof(RepositoryBase<,>));
            services.AddScoped<DbContext, ClaritysmsDbContext>();
            services.AddScoped<ITenantAppService, TenantAppService>();
            services.AddScoped<IUserAppService, UserAppService>();

**Comment by FabriDamazio** [comment]
Please add me in skype fabridamazio@hotmail.com
I need a closer look in your code.

**Comment by FabriDamazio** [comment]
The error is because you are using razor pages and the user session relies on the token information sent on the header of every request to set his own properties (like UserId).

@zaktecs maybe we need to implement a solution using cookies. Are you using cookies?



@zaktecsI can implement

**Comment by FabriDamazio** [comment]
@zaktecs [just created a sample](https://github.com/FabriDamazio/amplifier-aspnetcore-mvc-sample) using ASP.NET Core MVC template using cookie auth instead token:

**Comment by zaktecs** [comment]
@FabriDamazio you are amazing. 
The solution you have provided has solved my problem and even more. 
Many thanks
